version: "3.2"

services:
  fishbot:
    build:
      dockerfile: Dockerfile
      context: .
    environment:
      - IRC_HOST=${IRC_HOST}
      - IRC_PORT=${IRC_PORT}
      - NICKNAME=${NICKNAME}
      - IDENT=${IDENT}
      - REALNAME=${REALNAME}
      - AUTOMODES=${AUTOMODES}
      - DEFAULT_CHANNEL=${DEFAULT_CHANNEL}
      - ALLOW_INVITES=${ALLOW_INVITES}
